django/goal/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    # url(r'^profile/$', views.ProfileView.as_view(), name='global-profile'),
    url(
        r'^to/(?P<goal_slug>[\-\w]+)/profile/(?P<username>[\-\w]+)/$',
        views.ProfileView.as_view(),
        name='profile'
    ),
    url(r'^$', views.GoalsView.as_view(), name='home'),
    url(r'^new-goal$', views.NewGoalView.as_view(), name='new-goal'),
    url(
        r'^to/(?P<goal_slug>[\-\w]+)/join/$',
        views.JoinGoalView.as_view(),
        name='join-goal'
    ),
    url(
        r'^to/(?P<goal_slug>[\-\w]+)/$',
        views.GoalView.as_view(),
        name='goal'
    ),
    url(
        r'^to/(?P<goal_slug>[\-\w]+)/members/$',
        views.MembersView.as_view(),
        name='members'
    ),
    url(r'^to/(?P<goal_slug>[\-\w]+)/', include('suggestion.urls')),
    url(r'^to/(?P<goal_slug>[\-\w]+)/', include('review.urls')),
]

django/main/urls.py
from django import forms
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import static
from django.views.generic.base import RedirectView
from django.template import defaultfilters as filters

from registration.forms import RegistrationForm, TOS_REQUIRED
from registration.backends.hmac.views import RegistrationView


url_tos = r"https://github.com/mnieber/shared-goals/blob/master/TERMS.md"
url_about = r"https://github.com/mnieber/shared-goals/blob/master/README.md"
url_feedback = r"https://github.com/mnieber/shared-goals/issues"


class RegistrationFormWithTerms(RegistrationForm):
    # Subclass of ``RegistrationForm`` which adds a required checkbox
    # for agreeing to a site's Terms of Service.

    tos = forms.BooleanField(
        widget=forms.CheckboxInput,
        label=filters.safe((
            'I have read and agree to the '
            '<a href=%s>Terms of Service<a>'
        ) % url_tos),
        error_messages={
            'required': TOS_REQUIRED,
        }
    )


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(
        r'^accounts/register/$',
        RegistrationView.as_view(form_class=RegistrationFormWithTerms),
        name='registration_register'
    ),
    url(r'^tos/', RedirectView.as_view(url=url_tos), name='tos'),
    url(r'^about/', RedirectView.as_view(url=url_about), name='about'),
    url(
        r'^feedback/',
        RedirectView.as_view(url=url_feedback),
        name='feedback'
    ),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^notification/', include('notification.urls')),
    url(r'', include('goal.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(
            r'^media/(?P<path>.*)$',
            static.serve,
            {
                'document_root': settings.MEDIA_ROOT, 'show_indexes': True
            }
        ),
    ]

django/suggestion/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^new-suggestion/$',
        views.NewSuggestionView.as_view(),
        name='new-suggestion'
    ),
    url(
        r'^update-suggestion/(?P<suggestion_slug>[\-\w]+)/$',
        views.UpdateSuggestionView.as_view(),
        name='update-suggestion'
    ),
    url(
        r'^ajax-preview-suggestion/$',
        views.PreviewSuggestionView.as_view(),
        name='preview-suggestion'
    ),
    url(
        r'^by/(?P<suggestion_slug>[\-\w]+)/$',
        views.SuggestionView.as_view(),
        name='suggestion'
    ),
    url(
        r'^by/(?P<suggestion_slug>[\-\w]+)/revision/(?P<revision_pk>[\d]+)$',
        views.RevisionView.as_view(),
        name='revision'
    ),
]

django/review/models.py
"""Models for reviews."""

from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db import models

from goal.models import GlobalUser

from suggestion.models import Revision


class Review(models.Model):  # noqa
    EXPERIENCE_NOT_TRIED = 0
    EXPERIENCE_TRIED = 1
    EXPERIENCE_DOING = 2

    EXPERIENCE_CHOICES = (
        (EXPERIENCE_NOT_TRIED, "I've not tried this"),
        (EXPERIENCE_TRIED, "Yes, I've tried this myself"),
        (EXPERIENCE_DOING, "I've tried this, and I'm still doing it"),
    )

    pub_date = models.DateTimeField('date published', auto_now=True)
    owner = models.ForeignKey(GlobalUser)
    revision = models.ForeignKey(Revision, related_name="revisions", null=True)
    rating = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    description = models.TextField(blank=True)
    is_draft = models.BooleanField(default=True)
    experience = models.PositiveSmallIntegerField(
        choices=EXPERIENCE_CHOICES, default=0, blank=True)

    def __str__(self):  # noqa
        return "Review by %s for %s" % (self.owner, self.revision)

    @property
    def header(self):  # noqa
        header = self.owner.name
        header += ", %s" % naturaltime(self.pub_date)
        return header

    def published_comments(self):  # noqa
        comments = [
            c for c in self.comments.filter(
                is_draft=False, reply_to=None
            ).order_by("pub_date")
        ]

        result = []
        while len(comments):
            comment = comments.pop()
            result.append(comment)
            for reply in (
                comment.replies.filter(is_draft=False).order_by("pub_date")
            ):
                comments.append(reply)

        return result


class Comment(models.Model):  # noqa
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    owner = models.ForeignKey(GlobalUser)

    review = models.ForeignKey(Review, related_name="comments")
    reply_to = models.ForeignKey(
        'self', blank=True, null=True, related_name="replies")

    body = models.TextField()
    is_draft = models.BooleanField(default=True)

    def __str__(self):  # noqa
        return (
            "Comment by %s on %s (%s)"
            % (self.owner, self.review, self.reply_to_id)
        )

    def indent(self):  # noqa
        result = 0
        current = self
        while current.reply_to:
            result += 20
            current = current.reply_to
        return result

django/suggestion/models.py
"""Suggestion models."""

import emoji
import os

from django.contrib.humanize.templatetags.humanize import naturaltime
from django.core.urlresolvers import reverse
from django.db import models

from goal.utils import apply_cropping_to_image
from goal.models import Goal, GlobalUser


class Suggestion(models.Model):  # noqa
    TYPE_ACTION = 0
    TYPE_PRACTICE = 1

    TYPE_CHOICES = (
        (TYPE_ACTION, 'action'),
        (TYPE_PRACTICE, 'practice'),
    )

    goal = models.ForeignKey(Goal, related_name="suggestions")
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, default=0)
    avg_rating = models.DecimalField(
        max_digits=2, decimal_places=1, default=0.0)
    owner = models.ForeignKey(GlobalUser)
    is_draft = models.BooleanField(default=True)
    image = models.FileField(upload_to="suggestions", blank=True)
    uncropped_image = models.FileField(upload_to="suggestions", blank=True)
    slug = models.SlugField('slug', max_length=60)
    pub_date = models.DateTimeField('date published', auto_now=True)

    def __str__(self):  # noqa
        return self.slug + ("(draft)" if self.is_draft else "")

    def get_current_revision(self):  # noqa
        return self.revisions.latest('pub_date')

    def get_url(self):  # noqa
        return reverse(
            'suggestion',
            kwargs=dict(
                goal_slug=self.goal.slug, suggestion_slug=self.slug)
        )

    def stars(self):
        """Return a string with zero or more starts."""
        factor = int(round(self.avg_rating) if self.avg_rating else 0)
        return emoji.emojize(":star:", use_aliases=True) * factor

    def apply_cropping(self, crop):
        """Set self.image to the cropped self.ucropped_image."""
        apply_cropping_to_image(
            self.uncropped_image,
            crop['x'],
            crop['y'],
            crop['width'],
            crop['height'],
        )
        if (
            self.image and
            os.path.exists(self.image.path) and
            self.image.path != self.uncropped_image.path
        ):
            os.unlink(self.image.path)

        self.image.name = self.uncropped_image.name
        self.save()



class Revision(models.Model):  # noqa
    title = models.CharField(max_length=100)
    description = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now=True)
    suggestion = models.ForeignKey(Suggestion, related_name="revisions")

    def pub_date_display(self):  # noqa
        return naturaltime(self.pub_date)

    def __str__(self):  # noqa
        return "%s_%d" % (self.suggestion.slug, self.pk)

django/suggestion/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic import View
from django.utils.decorators import method_decorator

from goal.views import membership_required

from markdown_deux.templatetags.markdown_deux_tags import markdown_filter

from suggestion.forms import SuggestionForm
from suggestion.models import Suggestion, Revision


class PostSuggestionView(View):
    def on_cancel(self, goal_slug):
        # todo redirect to previous page
        return HttpResponseRedirect(
            reverse('goal', kwargs=dict(goal_slug=goal_slug))
        )

    def on_save(self, goal_slug, suggestion_slug):
        return HttpResponseRedirect(
            reverse(
                'suggestion',
                kwargs=dict(
                    goal_slug=goal_slug,
                    suggestion_slug=suggestion_slug
                )
            )
        )


class NewSuggestionView(PostSuggestionView):

    @method_decorator(membership_required)
    @method_decorator(login_required)
    def get(self, request, goal_slug):
        return self.handle(request, goal_slug)

    @method_decorator(membership_required)
    @method_decorator(login_required)
    def post(self, request, goal_slug):
        return self.handle(request, goal_slug)

    def handle(self, request, goal_slug):
        suggestion = SuggestionForm.get_or_create_draft(
            request.goal, request.global_user)
        is_posting = request.method == 'POST'
        submit = request.POST.get('submit', 'none')

        bound_form = None
        if is_posting:
            bound_form = SuggestionForm.get_posted_form(request, suggestion)
            should_accept_data = bound_form.update_suggestion_and_save(
                suggestion, submit)

            if should_accept_data and submit == 'save':
                return self.on_save(request.goal.slug, suggestion.slug)
            elif submit == 'cancel':
                return self.on_cancel(request.goal.slug)

        if is_posting and submit == 'save':
            form = bound_form
        else:
            form = SuggestionForm.get_populated_form(request, suggestion)

        context = {
            'form': form,
            'crop_settings': {
                'url': suggestion.image.url if suggestion.image else "",
                'klass': 'suggestion--image crop-image',
                'output_key': form.cropped_image_key,
                'jcrop': dict(
                    aspectRatio=360.0 / 200.0,
                    setSelect=[0, 0, 10000, 10000],
                ),
            },
            'show_image_form': True,
            'show_errors': submit == 'save',
            'post_button_label': 'Submit',
            'submit_button_header': (
                'All done, press Submit to publish your suggestion'
            ),
            'show_delete_button': False
        }

        return render(request, 'suggestion/edit_suggestion.html', context)


class UpdateSuggestionView(PostSuggestionView):

    @method_decorator(membership_required)
    @method_decorator(login_required)
    def get(self, request, goal_slug, suggestion_slug):
        return self.handle(request, goal_slug, suggestion_slug)

    @method_decorator(membership_required)
    @method_decorator(login_required)
    def post(self, request, goal_slug, suggestion_slug):
        return self.handle(request, goal_slug, suggestion_slug)

    def handle(self, request, goal_slug, suggestion_slug):
        suggestion = get_object_or_404(Suggestion, slug=suggestion_slug)
        is_posting = request.method == 'POST'
        submit = request.POST.get('submit', 'none')

        bound_form = None
        if is_posting:
            if submit == 'cancel':
                return self.on_cancel(request.goal.slug)
            if submit == 'delete':
                suggestion.delete()
                return self.on_cancel(request.goal.slug)

            bound_form = SuggestionForm.get_posted_form(request, suggestion)
            if bound_form.create_new_revision(suggestion):
                return self.on_save(request.goal.slug, suggestion.slug)

        form = (
            bound_form
            if is_posting else
            SuggestionForm.get_populated_form(request, suggestion)
        )

        context = {
            'form': form,
            'show_image_form': False,
            'show_errors': True,
            'post_button_label': "Update",
            'submit_button_header': 'Press Update to publish your changes',
            'show_delete_button': True,
        }

        return render(request, 'suggestion/edit_suggestion.html', context)


class PreviewSuggestionView(View):
    def post(self, request, goal_slug):
        return HttpResponse(markdown_filter(request.POST['text']))


class SuggestionView(View):
    def get(self, request, goal_slug, suggestion_slug):
        suggestion = get_object_or_404(Suggestion, slug=suggestion_slug)
        revision = suggestion.get_current_revision()

        context = {
            'suggestion': suggestion,
            'revision': revision,
        }
        return render(request, 'suggestion/suggestion.html', context)


class RevisionView(View):
    def get(self, request, goal_slug, suggestion_slug, revision_pk):
        revision = get_object_or_404(Revision, pk=revision_pk)

        context = {
            'suggestion': revision.suggestion,
            'revision': revision,
        }
        return render(request, 'suggestion/revision.html', context)

django/suggestion/templates/suggestion/edit_suggestion.html
{% extends 'base.html' %}
{% load notification_tags %}
{% load shared_goals_tags %}
{% load django_jcrop_tags %}
{% block content %}
  <div class="row small-gap-below">
    <div class="text-center">
      <h1>{{ request.goal.title }}</h1>
      <div class="button-grp">
        <button class="btn btn-default" onclick="location.href='{% url 'goal' request.goal.slug %}';">Suggestions</button>
        <button class="btn btn-default" onclick="location.href='{% url 'members' request.goal.slug %}';">Members</button>
        {% if request.global_user %}
          <button class="btn btn-default" onclick="location.href='{{ profile_url }}';">Profile
            {% with request.global_user.notifications|unread as unread_notifications %}
              {% if unread_notifications.count %} ({{ unread_notifications.count }}){% endif %}
            {% endwith %}
          </button>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <p>
          {% if show_errors %}{{ form.type.errors }}{% endif %}
          <label class="form-label" for="{{ form.type.id_for_label }}">Will you suggest a one-time Action, or a continuous Practice?</label>{{ form.type }}</p>
        <p>
          {% if show_errors %}{{ form.title.errors }}{% endif %}
          <label class="form-label" for="{{ form.title.id_for_label }}">Title</label>
          <input class="form-field" id="id_title" maxlength="100" name="title" type="text" value="{{ form.title.value }}">
        </p>
        <p>
          {% if show_errors %}{{ form.description.errors }}{% endif %}
          <label class="form-label" for="{{ form.description.id_for_label }}">Describe your suggestion
            <label class="form-label pull-right">
              <input id="chkPreview" type="checkbox">
              <span>Preview</span>
              <span style="font-size: 10px;">
                <a href="http://commonmark.org/help/">Markdown</a> allowed</span>
            </label>
          </label>
          <textarea class="form-field" id="description" name="description" rows="16">{{ form.description.value }}</textarea>
          <div class="tiny-gap-above small-gap-below" data-ajax-url="{% url 'preview-suggestion' request.goal.slug %}" id="descriptionPreview"></div>
        </p>
        {% if show_image_form %}{{ crop_settings|django_jcrop_widget }}
          <div class="suggestion-form--image">
            <p>
              {% if show_errors %}{{ form.image.errors }}{% endif %}
              <label class="form-label" for="{{ form.image.id_for_label }}">Make your suggestion look good by uploading an image</label>{{ form.image }}
              <button id="upload-submit" name="submit" value="upload">Upload</button>
            </p>
          </div>
        {% endif %}
        <div>
          <div class="small-gap-above small-gap-below">
            <label class="form-label">{{ submit_button_header }}</label>
            <button name="submit" value="save">{{ post_button_label }}</button>
            <button name="submit" value="cancel">Cancel</button>
          </div>
          {% if show_delete_button %}
            <button class="btn btn-danger suggestion--delete-button" name="submit" value="delete">Delete this suggestion</button>
          {% endif %}
        </div>
      </form>
    </div>
  </div>{% init_django_jcrop %}<script>
// suggestion/init_suggestion_form.js
$(document).ready(function() {
    var chkPreviewElm = $("#chkPreview");
    function onChkPreviewChanged() {
        var previewElm = $("#descriptionPreview");
        var descriptionElm = $("#description");
        url_get_preview = previewElm.data("ajax-url");
        var token = $("input[name='csrfmiddlewaretoken']").val();
        previewElm.load(
            url_get_preview,
            {
                csrfmiddlewaretoken: token,
                text: descriptionElm.val()
            }
        );
        if ($("#chkPreview").prop('checked')) {
            previewElm.removeClass("hidden-but-not-gone");
            descriptionElm.addClass("hidden-but-not-gone");
        }
        else {
            previewElm.addClass("hidden-but-not-gone");
            descriptionElm.removeClass("hidden-but-not-gone");
        }
        // previewElm.toggle($("#chkPreview").prop('checked'));
        // descriptionElm.toggle(!$("#chkPreview").prop('checked'));
    }
    chkPreviewElm.change(onChkPreviewChanged);
    onChkPreviewChanged();
});
</script>{% endblock %}

django/suggestion/templates/suggestion/revision.html
{% extends 'base.html' %}

{% load humanize %}
{% load markdown_deux_tags %}
{% load notification_tags %}
{% block content %}
  <div class="row small-gap-below">
    <div class="text-center">
      <h1>{{ request.goal.title }}</h1>
      <div class="button-grp">
        <button class="btn btn-default" onclick="location.href='{% url 'goal' request.goal.slug %}';">Suggestions</button>
        <button class="btn btn-default" onclick="location.href='{% url 'members' request.goal.slug %}';">Members</button>
        {% if request.global_user %}
          <button class="btn btn-default" onclick="location.href='{{ profile_url }}';">Profile
            {% with request.global_user.notifications|unread as unread_notifications %}
              {% if unread_notifications.count %} ({{ unread_notifications.count }}){% endif %}
            {% endwith %}
          </button>
        {% endif %}
      </div>
    </div>
  </div>
  {% with suggestion as the_suggestion %}
    {% with revision as the_revision %}
      <div class="row small-gap-below">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="suggestion--image" style="{% if the_suggestion.image %}background-image:url({{ the_suggestion.image.url }});{% endif %}">
            <div class="suggestion--gradient"></div>
            <span class="suggestion--title">
              <span class="title-caption">{{ the_suggestion.get_type_display }} {{ the_suggestion.stars }}</span>
              <h3>{{ the_revision.title }}</h3>
            </span>
          </div>
        </div>
      </div>
      <div class="row small-gap-below">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <p>This is a previous version of a 
            <a href="{% url 'suggestion' request.goal.slug suggestion.slug %}">suggestion</a> by {{ the_suggestion.owner.name }}</p>{{ the_revision.description|markdown }}</div>
      </div>
    {% endwith %}
  {% endwith %}
{% endblock %}

django/suggestion/templates/suggestion/suggestion.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% load humanize %}
{% load notification_tags %}
{% block content %}
  <div class="row small-gap-below">
    <div class="text-center">
      <h1>{{ request.goal.title }}</h1>
      <div class="button-grp">
        <button class="btn btn-default" onclick="location.href='{% url 'goal' request.goal.slug %}';">Suggestions</button>
        <button class="btn btn-default" onclick="location.href='{% url 'members' request.goal.slug %}';">Members</button>
        {% if request.global_user %}
          <button class="btn btn-default" onclick="location.href='{{ profile_url }}';">Profile
            {% with request.global_user.notifications|unread as unread_notifications %}
              {% if unread_notifications.count %} ({{ unread_notifications.count }}){% endif %}
            {% endwith %}
          </button>
        {% endif %}
      </div>
    </div>
  </div>
  {% with suggestion as the_suggestion %}
    {% with the_suggestion.get_current_revision as the_revision %}
      <div class="row small-gap-below">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="suggestion--image" style="{% if the_suggestion.image %}background-image:url({{ the_suggestion.image.url }});{% endif %}">
            <div class="suggestion--gradient"></div>
            <span class="suggestion--title">
              <span class="title-caption">{{ the_suggestion.get_type_display }} {{ the_suggestion.stars }}</span>
              <h3>{{ the_revision.title }}</h3>
            </span>
          </div>
        </div>
      </div>
      <div class="row small-gap-below">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h5>Published by {{ the_suggestion.owner.name }}, {{ the_suggestion.pub_date|naturaltime }}</h5>{{ the_revision.description|markdown }}</div>
      </div>
      <div id="sg-review-list"></div>
    {% endwith %}
  {% endwith %}<script>
// review/sg_comment_list.js
(function($) {
    function on_comment_form_submit(event) {
        event.preventDefault();

        // Send the data using post
        var form = $(this);
        var posting = $.post(
            form.data("ajax-url"),
            form.serialize() + "&submit=" + $(document.activeElement)[0].value
        );

        // Put the results in a div
        posting.done(function(data) {
            if (data.success) {
                form.closest(".sg-review").find(".sg-comment-list").sg_comment_list();
                // unload the form for replying to the review
                form.closest(".sg-review").find(".comment-reply-div").empty();
            }
        });
    }

    function init_reply_div() {
        // connect post button to do an ajax post
        form = $(this).find("form")[0];
        url_get_reply_form = $(this).data("ajax-url");
        $(form).data("ajax-url", url_get_reply_form);
        $(form).submit(on_comment_form_submit);
    }

    function on_click_reply_link() {
        // respond to clicking on $(this) reply link by showing a reply form
        reply_div = $(this).siblings(".comment-reply-div")[0];
        url_get_reply_form = $(this).data("ajax-url");
        $(reply_div).data("ajax-url", url_get_reply_form);
        $(reply_div).load(url_get_reply_form, init_reply_div);
    }

    $.fn.sg_comment_reply_link = function() {
        return this.each(function(dummy_index, reply_link) {
            $(reply_link).click(on_click_reply_link);
        });
    };
}(jQuery));


(function($) {
    $.fn.scroll_to_current_anchor = function() {
        var tmp = window.location.hash;
        window.location.hash = ""
        window.location.hash = tmp;
    };
}(jQuery));


(function($) {
    function init_comment_list() {
        // connect all reply-links within $(this) comment list
        $(this).find(".comment-reply-link").sg_comment_reply_link();

        // it's possible that the current anchor refers to a comment in
        // the list that was just loaded
        $().scroll_to_current_anchor();
    }

    $.fn.sg_comment_list = function() {
        return this.each(function(dummy_index, comment_list) {

            // load comments into this comment list
            url_get_comment_list = $(comment_list).data("ajax-url");
            $(comment_list).load(url_get_comment_list, init_comment_list);
        });
    };
}(jQuery));
</script><script>
// review/sg_review_list.js
(function($) {
    $.fn.sg_review_list = function() {
        return this.each(function(dummy_index, review_list_div) {

            $(review_list_div).find('div.rateit, span.rateit').rateit();
            $(review_list_div).find('.sg-comment-list').sg_comment_list();

            // connect link for replying to the review
            $(review_list_div).find('.comment-reply-link').sg_comment_reply_link();
        });
    };
}(jQuery));
</script><script>
// suggestion/init_suggestion.js
$(document).ready(function() {

    $("#sg-review-list").load(
        "{% url 'reviews' request.goal.slug suggestion.slug %}",
        function() {

            $('#rateit-review').bind('rated', function() {
                $('#id_rating').val($(this).rateit('value'));
            });

            $("#review-form").submit(function(event) {
                // Stop form from submitting normally
                event.preventDefault();

                // Send the data using post
                var posting = $.post(
                    $("#review-form").data("ajax-url"),
                    $(this).serialize() + "&submit=" + $(document.activeElement)[0].value
                );

                // Put the results in a div
                posting.done(function(data) {
                    $("#sg-review-list").html(data);
                    $("#sg-review-list").sg_review_list();
                });
            });

            $(this).sg_review_list();
        }
    );
});
</script>{% endblock %}